# This mode collects gt forget data and also gt retain data

expand_forget: False
expand_qanum: 0
expand_data_path: null
with_retain: True
retain_num: 400 #! adaptive to be equal to forget data
with_perturb: False
with_dpo: False